# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

ENV DEBIAN_FRONTEND=noninteractive

# Install Chromium browser
RUN apt-get update \
    && apt-get install -y chromium \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install Python dependencies and the MCP server
RUN pip install --no-cache-dir .

# Default entrypoint for MCP server
ENTRYPOINT ["mcp-server-nodriver"]
